Add Flag Embedding Reranker
Marker-Inc-Korea/AutoRAG pull request #277
Opened 2024-04-08 11:12 UTC by bwook00

close #275 
reference:
- https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/FlagEmbeddingReranker/
- https://github.com/FlagOpen/FlagEmbedding

2024-04-08 14:19 UTC, vkehfdl1 requested changes

2024-04-08 14:19 UTC, vkehfdl1 commented on docs/source/nodes/passage_reranker/flag_embedding_reranker.md
> +  model_name: "BAAI/bge-reranker-large"
delete "" in yaml file. No need

2024-04-08 14:19 UTC, vkehfdl1 commented on tests/autorag/nodes/passagereranker/test_flag_embedding.py
> +    original_sentence_transformer = flag_embedding_reranker.__wrapped__
`original_flag_embedding_reranker` will be fine.

2024-04-09 12:01 UTC, vkehfdl1 approved these changes
LGTM

2024-04-09 13:56 UTC, Eastsidegunn approved these changes

2024-04-09 13:56 UTC, merged