Add Hybrid DBSF(Distribution-based Score Fusion) retrieval
Marker-Inc-Korea/AutoRAG pull request #289
Opened 2024-04-10 05:42 UTC by bwook00

close #286 

https://medium.com/plain-simple-software/distribution-based-score-fusion-dbsf-a-new-approach-to-vector-search-ranking-f87c37488b18

2024-04-10 09:08 UTC, Eastsidegunn submitted a review, later dismissed
LGTM

2024-04-10 13:48 UTC, vkehfdl1 requested changes

2024-04-10 13:48 UTC, vkehfdl1 commented on tests/autorag/nodes/retrieval/test_hybrid_base.py
> +    assert result['retrieve_scores'].tolist()[0] == retrieve_scores
Why don't you use `pytest.approx`? Because of the floating point issue, the assertion of pure '==' can be False.

2024-04-10 13:48 UTC, vkehfdl1 commented on tests/autorag/nodes/retrieval/test_hybrid_dbsf.py
> +    assert result_scores == [[0.7041241452319316, 0.3979379273840342, 0.25],
Also, recommend to use pytest.approx

2024-04-11 05:59 UTC, vkehfdl1 approved these changes
LGTM

2024-04-11 08:08 UTC, Eastsidegunn approved these changes

2024-04-11 08:08 UTC, merged