Add how to use custom LLM(hosted privately) at docs
Marker-Inc-Korea/AutoRAG pull request #310
Opened 2024-04-11 13:27 UTC by bwook00

close #284

2024-04-11 14:18 UTC, vkehfdl1 requested changes

2024-04-11 14:18 UTC, vkehfdl1 commented on docs/source/local_model.md
> +📌 Of course, you can use `custom LLM` hosted privately!
It is confusing docs. Just add api_base parameter at above 'openailike' yaml file example.

2024-04-11 19:11 UTC, Eastsidegunn approved these changes

2024-04-11 19:11 UTC, Eastsidegunn commented
So simple

2024-04-12 05:40 UTC, vkehfdl1 approved these changes
LGTM

2024-04-12 05:47 UTC, merged