Add Recency filter module
Marker-Inc-Korea/AutoRAG pull request #312
Opened 2024-04-12 05:49 UTC by bwook00

close #293 

https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/RecencyPostprocessorDemo/
I see that the `recency filter` filters out information prior to the latest version, and decide that we should have a `recency filter` in addition to the time reranker.

- If all contents are filtered, keep the only one recency content.
- If the threshold date format is incorrect, return the original contents.

2024-04-12 07:15 UTC, vkehfdl1 requested changes

2024-04-12 07:15 UTC, vkehfdl1 commented on autorag/nodes/passagefilter/recency.py
> +        datetime_threshold = datetime.strptime(threshold, "%Y-%m-%d")
How about hour, minute, seconds? 
I think it needs to support YY-MM-DD hh:mm:ss format.

2024-04-12 07:15 UTC, vkehfdl1 commented on autorag/nodes/passagefilter/recency.py
> +                   threshold: str,
Why don't you get strptime type as parameter? Sometimes user wants to set threshold without hour:minute:seconds, sometimes day want to do.

2024-04-12 07:15 UTC, vkehfdl1 commented on tests/autorag/nodes/passagefilter/test_passage_filter_base.py
> +             [datetime(2021, 3, 1), datetime(2022, 3, 1), datetime(2030, 1, 1), datetime(2021, 1, 1)]]
add test case for hour, minutes, and seconds.

2024-04-12 07:15 UTC, vkehfdl1 commented on tests/autorag/nodes/passagefilter/test_recency_filter.py
> +        (contents_example, scores_example, ids_example, time_list, threshold="havertz")
![image](https://github.com/Marker-Inc-Korea/AutoRAG/assets/28955029/55f02cff-ae51-4e93-8dcd-a551e9b12d62)

2024-04-12 12:44 UTC, Eastsidegunn submitted a review, later dismissed
I think maybe we need some rule for expandable and flexable metadata format and filter structure in near future,,,
before, i need to do more things related to it.

LGTM

2024-04-12 13:06 UTC, bwook00 commented
> I think maybe we need some rule for expandable and flexable metadata format and filter structure in near future,,, before, i need to do more things related to it.
> 
> LGTM

I agree with you

2024-04-12 13:57 UTC, vkehfdl1 requested changes

2024-04-12 13:57 UTC, vkehfdl1 commented on autorag/nodes/passagefilter/recency.py
> +        logger.info("threshold date format is incorrect, should be YYYY-MM-DD or YYYY-MM-DD HH:MM:SS")
It suport YYYY-MM-DD HH:MM also

2024-04-12 13:57 UTC, vkehfdl1 commented on docs/source/nodes/passage_filter/recency_filter.md
> +  🚨 **threshold** format should be `YYYY-MM-DD` or `YYYY-MM-DD HH:MM:SS`🚨
Fix doc who do not want to use second. only hour and minutes

2024-04-13 08:39 UTC, vkehfdl1 commented
> I think maybe we need some rule for expandable and flexable metadata format and filter structure in near future,,, before, i need to do more things related to it.

What is 'expandable' and 'flexible' metadata format? We support metadata dictionary. Use any 'key' and value already... 
Maybe you mean the retrieval module using metadatas??

2024-04-13 08:39 UTC, vkehfdl1 approved these changes

2024-04-14 10:57 UTC, Eastsidegunn approved these changes

2024-04-14 10:57 UTC, merged