Add refine module
Marker-Inc-Korea/AutoRAG pull request #323
Opened 2024-04-12 12:36 UTC by bwook00

close #321 

https://docs.llamaindex.ai/en/stable/examples/response_synthesizers/refine/

2024-04-12 13:47 UTC, vkehfdl1 requested changes

2024-04-12 13:47 UTC, vkehfdl1 commented on tests/autorag/nodes/passagecompressor/test_refine.py
> +from tests.autorag.nodes.passagecompressor.test_tree_summarize import queries, retrieved_contents, check_result, df
Make new 'test_base_passage_compressor' python file inside test folder and save queries, df etc. at there.
Importing from other modules test file can occur error like circular import.

2024-04-13 08:41 UTC, vkehfdl1 approved these changes

2024-04-14 10:57 UTC, Eastsidegunn approved these changes

2024-04-15 05:47 UTC, merged