Created Contributors file
Marker-Inc-Korea/AutoRAG pull request #348
Opened 2024-04-17 16:46 UTC by gauravsaini02

I have added 2 files under Workflows directory.
1. Contributors.md : Explaining about the steps to be taken to contribute.
2. CODE_OF_CONDUCT.md : Explaining the ethics to be followed while contributing

2024-04-18 00:56 UTC, vkehfdl1 requested changes
Hi @gauravsaini02 Thanks for your first contribution.
Overall, it is great.
But, there are minor changes to be done.
Plus, two things need to be changed.

1. Move two .md files to root folder. I don't know why these file in .github/workflows directory.
2. Change contributors.md name to `CONTRIBUTING.md`

2024-04-18 00:56 UTC, vkehfdl1 commented on .github/workflows/CODE_OF_CONDUCT.md
> +Reports of abusive, harassing, or otherwise inappropriate behavior can be sent to info@mifos.org, the project team's email address. After each complaint is examined and looked into, a response that i
You can change this e-mail address to 'jeffrey@markr.ai' and 'vkehfdl1@gmail.com'

2024-04-18 00:56 UTC, vkehfdl1 commented on .github/workflows/contributors.md
> +- Include mockups for UI improvements or procedures to obtain a clear understanding.
We don't have UI yet, so delete 'UI improvements' at here.

2024-04-18 00:56 UTC, vkehfdl1 commented on .github/workflows/contributors.md
> +- If there are any, including screenshots (especially for UI-related concerns).
Do not need 
`(especially for UI-related concerns)`

2024-04-18 07:38 UTC, vkehfdl1 approved these changes
LGTM

2024-04-18 07:41 UTC, bwook00 approved these changes
LGTM! Thanks for your first contribution 👍 👍

2024-04-18 09:00 UTC, gauravsaini02 commented
The checks have failed for my files. Kindly let me know the possible reason and its solution.

2024-04-19 00:24 UTC, vkehfdl1 commented
@gauravsaini02  We are figuring out how can we pass your test. 

One of the solution is to set your own API key at github secrets on your forked repository.

Go to forked repository > Settings > Secrets and Variables > Actions and set Repository Secrets.
You have to set OPENAI_API_KEY, JINAAI_API_KEY, and COHERE_API_KEY.

Sorry for the process. Me and @bwook00 will find a way that you don't have to set those variables. 
If you want to pass it quickly, please set the secrets. Or you can wait for the solution. Thank you.

2024-04-19 08:41 UTC, vkehfdl1 commented
@gauravsaini02 I send a PR for resolving test issue.
https://github.com/Marker-Inc-Korea/AutoRAG/pull/354
Please wait for this will be merged, and the next time your PR will be merged. Thanks

2024-04-21 06:12 UTC, merged

2024-04-21 06:19 UTC, gauravsaini02 commented
Hi Dear,
Thanks a lot....
I was looking forward to contribute to technical part in upcoming future. This issue will still create trouble i guess...