Add AutoParse baseline and module 'langchain_parse' and 'clova'
Marker-Inc-Korea/AutoRAG pull request #660
Opened 2024-08-29 14:13 UTC by bwook00

Plan to write docs after code review ^^

2024-08-30 03:02 UTC, vkehfdl1 requested changes

2024-08-30 03:02 UTC, vkehfdl1 commented on tests/autorag/data/parse/test_clova_ocr.py
> +		expect_text = file.read()
You can make "result_sample.json" and "result_text.txt" to the pytest fixture

2024-08-30 05:13 UTC, bwook00 commented on autorag/parser.py
> +		return module_list, combination_list
This function comes from `Node` class `get_param_combinatios`, but it is little bit different code! So I think this function should be here! how do you think about this?

2024-08-31 03:23 UTC, vkehfdl1 commented on autorag/parser.py
> +		return module_list, combination_list
I didn't notice the difference

2024-08-31 03:25 UTC, vkehfdl1 requested changes

2024-08-31 03:25 UTC, vkehfdl1 commented on autorag/data/parse/clova.py
> +	image_name_list = generate_image_names(pdf_path, len(image_data_list))
Just delete pdf_to_images and use below
```
image_data_list = convert_pdf_to_images(pdf_path)
image_name_list = generate_image_names(pdf_path, len(image_data_list))
```
at clove_pure function?

2024-09-01 09:27 UTC, vkehfdl1 approved these changes
LGTM

2024-09-01 09:27 UTC, merged