add metric and reform style
Marker-Inc-Korea/AutoRAG pull request #750
Opened 2024-09-26 16:50 UTC by Eastsidegunn

add metric and reform style

2024-09-27 06:25 UTC, vkehfdl1 requested changes
Did you use pre-commit and ruff format???
I think there is not formatted well or is it formatting all code again?

2024-09-27 06:25 UTC, vkehfdl1 commented on autorag/schema/metricinput.py
> +			expected_output=self.generation_gt[0]
Do you not compute multiple generation_gt?

2024-09-27 06:25 UTC, vkehfdl1 commented on autorag/schema/metricinput.py
> +from deepeval.test_case import LLMTestCase
import deepeval inside the `to_deepeval_testcase` 
Because I don't want deepeval import everytime use `MetricInput`.

2024-10-04 17:13 UTC, vkehfdl1 commented
@bwook00 

- Add deepeval faithfulness metric (see the prompt and the generation.py)
- Add `structure_output` functions at Generators. We can use structure output from our generator directly now. It uses more concise metric output that uses LLM judges. (We can update G-eval to support all generator modules)
- Do not run github action test on the all **legacy** qa data creation cases. Do not need it anymore.
- Many reformats. I don't know why this files reformatted. But maybe we have to make ruff format test on the CI/CD for checking it force (We can't see the difference non-ruff and yes-ruff easily)
- Delete RAGAS and guidance dependencies.

2024-10-05 04:04 UTC, bwook00 approved these changes
LGTM

2024-10-05 05:02 UTC, vkehfdl1 approved these changes

2024-10-05 05:02 UTC, merged