Add FlashRank Reranker module
Marker-Inc-Korea/AutoRAG pull request #818
Opened 2024-10-09 13:27 UTC by bwook00

close #775

2024-10-10 07:11 UTC, vkehfdl1 requested changes

2024-10-10 07:11 UTC, vkehfdl1 commented on autorag/nodes/passagereranker/flashrank.py
> +import onnxruntime as ort
import this inside each class.

This is the new rule at the newest version. 
For using separate dependency between api and gpu(local) version.

2024-10-10 07:11 UTC, vkehfdl1 commented
@bwook00 You need to add onnxruntime dependency as well

2024-10-11 06:29 UTC, bwook00 commented
I'll do it after pr #823 was merged

2024-10-11 15:11 UTC, vkehfdl1 approved these changes
LGTM

2024-10-11 15:11 UTC, merged