Create passage_reranker decorator and run.py
Marker-Inc-Korea/AutoRAG pull request #88
Opened 2024-01-31 19:38 UTC by bwook00

2024-01-31 20:13 UTC, vkehfdl1 requested changes

2024-01-31 20:13 UTC, vkehfdl1 commented on autorag/nodes/passagereranker/run.py
> +                                                    'retrieval_f1', 'retrieval_recall'])
Do not drop retrieval_f1 and retrieval_recall.

2024-02-01 08:50 UTC, Eastsidegunn approved these changes

2024-02-01 08:53 UTC, vkehfdl1 approved these changes
LGTM

2024-02-01 08:53 UTC, merged