Add `tqdm` progress bars to various methods and commands
Marker-Inc-Korea/AutoRAG pull request #890
Opened 2024-10-25 20:24 UTC by rohitg00

* **`autorag/__init__.py`**
  - Import `tqdm` for progress bar support

* **`autorag/chunker.py`**
  - Add `tqdm` progress bar to `start_chunking` method

* **`autorag/cli.py`**
  - Add `tqdm` progress bar to `evaluate` command
  - Add `tqdm` progress bar to `run_api` command
  - Add `tqdm` progress bar to `run_web` command

2024-10-25 20:25 UTC, rohitg00 commented
Proposed changes for the feature request: https://github.com/Marker-Inc-Korea/AutoRAG/issues/878

2024-10-26 12:22 UTC, vkehfdl1 requested changes
Also the other things.
Simply add tqdm range at the non-iteratable objects do not improve user experience.
I really appreciate your PR and your time to work on this. 
But we are working on a solution that are not using log. Because we think we are using tqdm and logger with `rich` pretty well along the cli.

However, as you feel the same, only using cli terminal and seeing the log is really hard to recognize the process. Actually we log all the info of the initializing, running, and deleting each module and tracking each module execution.
But yet, it is hard to recognize.

Maybe it is our fault that do not write an issue specification well.

Anyway, it is hard to accept this code for our main branch because it seems to add unmeaningful log at the terminal. 

Thanks for the interest to our project, and I hope we can find the good part to the contribution to our project.

2024-10-26 12:22 UTC, vkehfdl1 commented on autorag/chunker.py
> +			)
I don’t figure out the reason why the tqdm range shown in here. It is not that different between `logger.info` about chunking done.

2024-10-30 06:29 UTC, vkehfdl1 commented
close this at #903

2024-10-30 06:29 UTC, closed without merging